### ISSUE TITLE
How to upload the data file in Watson Studio

### ISSUE THREAD

**Issue by charul72** [IBM/product-recommendation-with-watson-ml#22]
The below link states:
https://github.com/IBM/product-recommendation-with-watson-ml/blob/master/notebooks/wml-product-recommendation-engine.ipynb

Before you use the sample code in this notebook, you must perform the following setup tasks:
Create a Watson Machine Learning service instance (a free plan is offered) and associate it with your project
Upload heart failure data to the Object Store service that is part of Watson Studio

How to do the above steps? and how to reference  the file as pandas.read_csv...

**Comment by stevemar** [comment]
@charul72 hi, that step is not required, I removed it. The data should be loaded in the next few cells.
